server:
  port: 8713
spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      routes:
        #路由 provider-server 访问：http://localhost:8713/provider/hello
        - id: provider-router
          uri: lb://provider-server
          predicates:
            - Path=/provider/**
        #路由 customer-server 访问：http://localhost:8713/customer/hello
        - id: customer-router
          uri: lb://customer-server
          predicates:
            - Path=/customer/**
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka