server:
  port: 8761
spring:
  application:
    name: eureka-service
#  cloud:
#    gateway:
#      routes:
#        - id: provider-router
#          uri: lb://provider-server
#          predicates:
#            - Path=/provider/**
#        - id: customer-router
#          uri: lb://customer-server
#          predicates:
#            - Path=/customer/**
#      enabled: false
  #解决添加gateway依赖后spring-boot-starter-web冲突
#  main:
#    web-application-type: reactive
#    allow-bean-definition-overriding: true
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
#      defaultZone: http://localhost:8761/eureka